FROM golang:1.13 as builder

WORKDIR /temp

COPY go.mod .
COPY go.sum .

RUN go get -v -t -d ./...

COPY . .

######## Start a new stage from scratch #######
FROM alpine:latest
RUN apk --no-cache --update upgrade && apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /temp .
COPY --from=0 /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

EXPOSE 8080

# Run the executable
ENTRYPOINT ["./mccs", "-config=production"]
CMD []
