FROM golang:1.13

WORKDIR /usr/src/app

COPY go.mod .
COPY go.sum .

RUN go get -v -t -d ./...
RUN go get github.com/cespare/reflex

ENV CONFIG test

CMD ["go", "test", "-coverprofile=coverage.txt", "-cover", "-v", "-race", "./..."]
# CMD ["reflex", "-c", "./reflex.test.conf"]
